package LeetCode;

/**
 * @author Srunkyo
 * @Date: 2018/7/28
 * @Description:
 * Easy
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class Problem389_FindTheDifference {
    // O(n) O(n)
    public char findTheDifference(String s, String t) {
        int[] mask = new int[26];
        for (char c : s.toCharArray()) {
            mask[c - 'a'] += 1;
        }
        for (char c : t.toCharArray()) {
            mask[c - 'a'] -= 1;
            if (mask[c - 'a'] < 0) {
                return c;
            }
        }
        return '0';
    }

    // O(n) O(1)
    public char findTheDifference2(String s, String t) {
        int sum = 0;
        for (char c : t.toCharArray()) {
            sum += c;
        }
        for (char c : s.toCharArray()) {
            sum -= c;
        }
        return (char)sum;
    }



}
